In [5]:
import pandas as pd

In [7]:
import numpy as np

In [8]:
string_data = pd.Series(['aardvark','artichoke',np.nan, 'avocado'])

In [9]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [10]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [11]:
string_data[0] = None

In [13]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [14]:
from numpy import nan as NA

In [15]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [16]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [17]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [18]:
data = pd.DataFrame([[1.,6.5,3.], [1.,NA,NA], [NA,NA,NA], [NA,6.5,3.]])

In [19]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
cleaned = data.dropna()

In [21]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [22]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [23]:
df = pd.DataFrame(np.random.randn(7,3))

In [24]:
df

0         1         2
0 -0.853195  1.125987  0.037845
1  0.016236  0.174023  0.039786
2 -0.677742 -0.920321  1.573284
3 -0.417508  0.933408 -0.030034
4 -1.558066  0.492087  0.451411
5  0.529493 -0.849050  0.881777
6  1.092071  0.362736  1.221283

In [25]:
df.iloc[:4,1] = NA

In [26]:
df.iloc[:2,2] = NA

In [27]:
df

0         1         2
0 -0.853195       NaN       NaN
1  0.016236       NaN       NaN
2 -0.677742       NaN  1.573284
3 -0.417508       NaN -0.030034
4 -1.558066  0.492087  0.451411
5  0.529493 -0.849050  0.881777
6  1.092071  0.362736  1.221283

In [28]:
df.dropna()

0         1         2
4 -1.558066  0.492087  0.451411
5  0.529493 -0.849050  0.881777
6  1.092071  0.362736  1.221283

In [29]:
df.dropna(thresh=2)

0         1         2
2 -0.677742       NaN  1.573284
3 -0.417508       NaN -0.030034
4 -1.558066  0.492087  0.451411
5  0.529493 -0.849050  0.881777
6  1.092071  0.362736  1.221283

In [30]:
df.fillna(0)

0         1         2
0 -0.853195  0.000000  0.000000
1  0.016236  0.000000  0.000000
2 -0.677742  0.000000  1.573284
3 -0.417508  0.000000 -0.030034
4 -1.558066  0.492087  0.451411
5  0.529493 -0.849050  0.881777
6  1.092071  0.362736  1.221283

In [31]:
df.fillna{1:0.5,2:0}

SyntaxError: invalid syntax (<ipython-input-31-ef4321794348>, line 1)

In [32]:
df.fillna({1:0.5,2:0})

0         1         2
0 -0.853195  0.500000  0.000000
1  0.016236  0.500000  0.000000
2 -0.677742  0.500000  1.573284
3 -0.417508  0.500000 -0.030034
4 -1.558066  0.492087  0.451411
5  0.529493 -0.849050  0.881777
6  1.092071  0.362736  1.221283

In [33]:
_ = df.fillna(0, inplace=True)

In [34]:
df

0         1         2
0 -0.853195  0.000000  0.000000
1  0.016236  0.000000  0.000000
2 -0.677742  0.000000  1.573284
3 -0.417508  0.000000 -0.030034
4 -1.558066  0.492087  0.451411
5  0.529493 -0.849050  0.881777
6  1.092071  0.362736  1.221283

In [41]:
df = pd.DataFrame(np.random.randn(6,3))

In [42]:
df.iloc[2:,1] = NA

In [43]:
df.iloc[4:,2] = NA

In [44]:
df

0         1         2
0  2.359531 -0.594428 -0.609079
1 -0.553016  0.114287  0.379001
2 -1.491324       NaN -0.812487
3  0.077632       NaN  1.156562
4 -0.037351       NaN       NaN
5  0.810785       NaN       NaN

In [45]:
df.fillna(method='ffill')

0         1         2
0  2.359531 -0.594428 -0.609079
1 -0.553016  0.114287  0.379001
2 -1.491324  0.114287 -0.812487
3  0.077632  0.114287  1.156562
4 -0.037351  0.114287  1.156562
5  0.810785  0.114287  1.156562

In [46]:
df.fillna(method='ffill',limit=2)

0         1         2
0  2.359531 -0.594428 -0.609079
1 -0.553016  0.114287  0.379001
2 -1.491324  0.114287 -0.812487
3  0.077632  0.114287  1.156562
4 -0.037351       NaN  1.156562
5  0.810785       NaN  1.156562

In [47]:
data = pd.Series([1.,NA,3.5,NA,7])

In [49]:
data.fillna(np.mean(data))

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [51]:
%time data.fillna(np.mean(data))

Wall time: 994 µs


0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [52]:
%time data.fillna(data.mean())

Wall time: 0 ns


0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [53]:
data = pd.DataFrame({'k1':['one','two'] *3 + ['two'], 'k2':[1,1,2,3,3,4,4]})

In [54]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [55]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [56]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [57]:
data['v1'] = range(7)

In [58]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [59]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [60]:
data.drop_duplicates(['k1','k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [61]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'], 'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [62]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [63]:
meat_to_animal={'bacon':'pig', 'pulled pork':'pig', 'pastiami':'cow','corned beef':'cow', 'honey ham':'pig', 'nova lox':'salmon'}

In [64]:
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastiami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [65]:
lowercased = data['food'].str.lower()

In [66]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [67]:
data['animal'] = lowercased.map(meat_to_animal)

In [68]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     NaN
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     NaN
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [69]:
meat_to_animal={'bacon':'pig', 'pulled pork':'pig', 'pastrami':'cow','corned beef':'cow', 'honey ham':'pig', 'nova lox':'salmon'}

In [70]:
data['animal'] = lowercased.map(meat_to_animal)

In [71]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [72]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [73]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [75]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [76]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [77]:
data = pd.DataFrame(np.arange(12).reshape((3,4)), index = ['Ohio','Colorado','New York'], columns = ['one','two','three','four'])

In [78]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [79]:
transform = lambda x : x[:4].upper()

In [80]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [81]:
data.index = data.index.map(transform)

In [82]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [83]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [84]:
str.title?

In [85]:
data.rename(index={'OHIO':'INDIANA'}, columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [86]:
data.rename(index={'OHIO':'INDIANA'}, inplace=True)

In [87]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [88]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]

In [89]:
bins = [18,25,35,60,100]

In [90]:
cats = pd.cut(ages, bins)

In [91]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [92]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [93]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [94]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [95]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']

In [96]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [97]:
data = np.random.randn(20)

In [98]:
pd.cut(data, 4, precision=2)

[(-1.41, -0.61], (0.18, 0.97], (-0.61, 0.18], (-0.61, 0.18], (0.18, 0.97], ..., (0.97, 1.76], (-0.61, 0.18], (-0.61, 0.18], (0.18, 0.97], (-1.41, -0.61]]
Length: 20
Categories (4, interval[float64]): [(-1.41, -0.61] < (-0.61, 0.18] < (0.18, 0.97] < (0.97, 1.76]]

In [99]:
data = np.random.randn(1000)

In [100]:
cats = pd.qcut(data, 4)

In [101]:
cats

[(0.583, 2.522], (-0.691, -0.0269], (-0.691, -0.0269], (0.583, 2.522], (-3.711, -0.691], ..., (-0.0269, 0.583], (-3.711, -0.691], (-3.711, -0.691], (-3.711, -0.691], (-3.711, -0.691]]
Length: 1000
Categories (4, interval[float64]): [(-3.711, -0.691] < (-0.691, -0.0269] < (-0.0269, 0.583] < (0.583, 2.522]]

In [102]:
pd.value_counts(cats)

(0.583, 2.522]       250
(-0.0269, 0.583]     250
(-0.691, -0.0269]    250
(-3.711, -0.691]     250
dtype: int64

In [103]:
data = pd.DataFrame(np.random.randn(1000,4))

In [104]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.023599    -0.036069    -0.016761    -0.011645
std       0.966735     1.019376     0.952757     1.020170
min      -3.128280    -3.033703    -3.257832    -2.856390
25%      -0.657262    -0.694397    -0.655714    -0.678074
50%       0.012176    -0.048674     0.009474    -0.026444
75%       0.638114     0.652194     0.588200     0.675551
max       2.848198     3.027715     2.869168     3.012577

In [105]:
col = data[2]

In [106]:
col[np.abs(col)>3]

701   -3.257832
Name: 2, dtype: float64

In [107]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
71  -0.782134  3.027715  0.830106 -0.967031
75  -3.128280 -1.211144  0.290766 -0.877602
445 -1.720452  1.476984 -0.831789  3.004905
482 -0.828230 -3.033703  0.829043 -1.461302
558 -3.034831  1.587787 -1.602233 -0.040187
701  0.284390 -0.049714 -3.257832  0.907494
800 -0.390826 -1.194834 -1.509538  3.012577

In [108]:
data[np.abs(data)>3] = np.sign(data) * 3

In [109]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.023436    -0.036063    -0.016503    -0.011663
std       0.966223     1.019194     0.951913     1.020118
min      -3.000000    -3.000000    -3.000000    -2.856390
25%      -0.657262    -0.694397    -0.655714    -0.678074
50%       0.012176    -0.048674     0.009474    -0.026444
75%       0.638114     0.652194     0.588200     0.675551
max       2.848198     3.000000     2.869168     3.000000

In [110]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0  1.0
1 -1.0  1.0 -1.0  1.0
2  1.0  1.0 -1.0  1.0
3  1.0  1.0 -1.0 -1.0
4 -1.0  1.0 -1.0 -1.0

In [112]:
df=pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [113]:
sampler = np.random.permutation(5)

In [114]:
sampler

array([2, 0, 4, 3, 1])

In [115]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [116]:
df.take(sampler)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
4  16  17  18  19
3  12  13  14  15
1   4   5   6   7

In [117]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15

In [119]:
df.loc[:2,:]

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [120]:
choices = pd.Series([5,7,-1,6,4])

In [121]:
draws = choices.sample(n=10,replace=True)

In [122]:
draws

4    4
1    7
3    6
1    7
0    5
2   -1
3    6
1    7
3    6
2   -1
dtype: int64

In [123]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'], 'data1':range(6)})

In [124]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [125]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [126]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [127]:
df_with_dummy = df[['data1']].join(dummies)

In [128]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [129]:
pd.get_dummies?

In [130]:
mnames = ['movie_id','title','genres']

In [136]:
movies = pd.read_csv('ml-latest/ml-latest/movies.csv',header = None, names=mnames)

In [140]:
movies[:10]

movie_id                               title  \
0         1                    Toy Story (1995)   
1         2                      Jumanji (1995)   
2         3             Grumpier Old Men (1995)   
3         4            Waiting to Exhale (1995)   
4         5  Father of the Bride Part II (1995)   
5         6                         Heat (1995)   
6         7                      Sabrina (1995)   
7         8                 Tom and Huck (1995)   
8         9                 Sudden Death (1995)   
9        10                    GoldenEye (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy  
5                        Action|Crime|Thriller  
6                               Comedy|Romance  
7                           Adventure|Children  
8                                       Action  
9                    Action|Adventure|Thriller

In [141]:
all_genres = []

In [142]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [143]:
genres = pd.unique(all_genres)

In [144]:
genres

array(['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Mystery', 'Sci-Fi', 'IMAX', 'Documentary', 'War', 'Musical',
       'Western', 'Film-Noir', '(no genres listed)'], dtype=object)

In [145]:
zero_matrix = np.zeros((len(movies),len(genres)))

In [146]:
dummies = pd.DataFrame(zero_matrix, columns = genres)

In [147]:
gen = movies.genres[0]

In [148]:
gen.split('|')

['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy']

In [150]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2, 3, 4], dtype=int64)

In [152]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1

In [153]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [154]:
movies_windic.iloc[0]

movie_id                                                              1
title                                                  Toy Story (1995)
genres                      Adventure|Animation|Children|Comedy|Fantasy
Genre_Adventure                                                       1
Genre_Animation                                                       1
Genre_Children                                                        1
Genre_Comedy                                                          1
Genre_Fantasy                                                         1
Genre_Romance                                                         0
Genre_Drama                                                           0
Genre_Action                                                          0
Genre_Crime                                                           0
Genre_Thriller                                                        0
Genre_Horror                                                    

In [155]:
a = 'b,c,d'

In [156]:
type(a.split(','))

list

In [157]:
pd.unique?

In [158]:
%time genres = pd.unique(all_genres)

Wall time: 16.4 ms


In [159]:
%time genres = list(set(all_genres))

Wall time: 6.99 ms


In [160]:
genres_2 = list(set(all_genres))

In [161]:
genres = pd.unique(all_genres)

In [162]:
genres== genres_2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [163]:
np.in1d(genres, genres_2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [164]:
np.in1d(genres_2, genres)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [167]:
np.intersect1d(genres, genres_2) == []

<ipython-input-167-d4575f3f5984>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.intersect1d(genres, genres_2) == []


False

In [168]:
np.intersect1d(genres, genres_2)

array(['(no genres listed)', 'Action', 'Adventure', 'Animation',
       'Children', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
       'Film-Noir', 'Horror', 'IMAX', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western'], dtype=object)

In [170]:
genres_2

['Comedy',
 'Documentary',
 'Action',
 'Western',
 'Crime',
 'Fantasy',
 'Mystery',
 'Musical',
 'Children',
 'Romance',
 'Film-Noir',
 'Drama',
 'Animation',
 'Horror',
 'IMAX',
 'Thriller',
 '(no genres listed)',
 'Adventure',
 'War',
 'Sci-Fi']

In [171]:
type(genres_2)

list

In [172]:
genres

array(['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Mystery', 'Sci-Fi', 'IMAX', 'Documentary', 'War', 'Musical',
       'Western', 'Film-Noir', '(no genres listed)'], dtype=object)

In [173]:
type(genres)

numpy.ndarray

In [174]:
val = 'a,b, guido'

In [175]:
val.split(',')

['a', 'b', ' guido']

In [176]:
pieces = [x.strip() for x in val.split(',')]

In [177]:
pieces

['a', 'b', 'guido']

In [178]:
first, second, third  = pieces

In [179]:
first + '::' + second + '::' + third

'a::b::guido'

In [180]:
'::'.join(pieces)

'a::b::guido'

In [181]:
'guido' in val

True

In [182]:
val.index(',')

1

In [183]:
val.find(':')

-1

In [184]:
 import re

In [185]:
text = "foo ber\t baz \tquz"

In [186]:
text

'foo ber\t baz \tquz'

In [187]:
text = "foo ber|t baz |tquz"

In [188]:
text

'foo ber|t baz |tquz'

In [189]:
text = "foo ber\t baz \tquz"

In [190]:
re.split('\s+', text)

['foo', 'ber', 'baz', 'quz']

In [191]:
regex = re.compile('\s+')

In [192]:
regex.split(text)

['foo', 'ber', 'baz', 'quz']

In [193]:
regex.findall(text)

[' ', '\t ', ' \t']

In [194]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [195]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [196]:
m = regex.search(text)

In [197]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [198]:
text[m.start():m.end()]

'dave@google.com'

In [199]:
regex.match(text)

In [200]:
print(regex.match(text))

None


In [201]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [205]:
m.groups()

()

In [208]:
m = regex.match('wesm@bright.net')

In [209]:
m.groups()

()

In [210]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [211]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [212]:
m = regex.match('wesm@bright.net')

In [213]:
m.groups()

('wesm', 'bright', 'net')

In [214]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [215]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



In [216]:
data = {'Dave':'dave@google.com', 'Steve':'steve@gmail.com','Rob':'rob@gamil.com','Wes':np.nan}

In [217]:
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gamil.com',
 'Wes': nan}

In [218]:
data = pd.Series(data)

In [219]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gamil.com
Wes                  NaN
dtype: object

In [220]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [221]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob      False
Wes        NaN
dtype: object

In [222]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [223]:
data.str.findall(pattern, flags = re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gamil, com)]
Wes                        NaN
dtype: object

In [224]:
str.get?

Object `str.get` not found.


In [225]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [226]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [229]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object