In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4,-7,-5,3])

In [4]:
obj

0    4
1   -7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4, -7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'], 'year':[2000,2001,2002,2001,2002,2003], 'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [8]:
frame = pd.DataFrame(data)

In [9]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [10]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [11]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'], index=['one','two','three','four','five','six'])

In [12]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [13]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [14]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [15]:
type(frame2.state)

pandas.core.series.Series

In [16]:
frame2[['state','pop']]

state  pop
one      Ohio  1.5
two      Ohio  1.7
three    Ohio  3.6
four   Nevada  2.4
five   Nevada  2.9
six    Nevada  3.2

In [17]:
type(frame2[['state','pop']])

pandas.core.frame.DataFrame

In [18]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [19]:
frame2['debt']=16.5

In [20]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [21]:
import numpy as np

In [22]:
frame2['debt'] = np.arange(6.)

In [23]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [24]:
val = pd.Series([-1.2,-1.5,-1.7], index = ['two','four','five'])

In [25]:
frame['debt'] = val

In [26]:
frame2['debt'] = val

In [27]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [28]:
frame['eastern'] = frame2.state == 'Ohio'

In [29]:
frame2['eastern'] = frame2.state == 'Ohio'

In [30]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [31]:
del frame2['eastern']

In [32]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [33]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [34]:
pop = {'Nevada':{2001:2.4, 2002:2.9}, 'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}

In [35]:
frame3 = pd.DataFrame(pop)

In [36]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [37]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [38]:
obj = pd.Series(range(3), index=['a','b','c'])

In [39]:
index = obj.index

In [40]:
type(obj.index)

pandas.core.indexes.base.Index

In [41]:
index

Index(['a', 'b', 'c'], dtype='object')

In [42]:
index[1:]

Index(['b', 'c'], dtype='object')

In [43]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [44]:
labels = pd.Index(np.arange(3))

In [45]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [46]:
obj2 = pd.Series([1.5,-2.5,0], index = labels)

In [47]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [48]:
obj2.index is labels

True

In [49]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [50]:
frame3.index.name = 'year'

In [51]:
frame3.columns.name = 'state'

In [52]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [53]:
'Ohio' in frame3.columns

True

In [54]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [55]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [56]:
obj = pd.Series([4.5, 7.2,-5.3, 3.6], index = ['d', 'b', 'a', 'c'])

In [57]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [58]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [59]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [60]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])

In [61]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [62]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [63]:
frame = pd.DataFrame(np.arange(9).reshape(3,3), index = ['a','c','d'], columns = ['Ohio','Texas','California'])

In [64]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [65]:
frame.reindex(['a','b','c','d'])

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [66]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [67]:
frame2 = frame.reindex(['a','b','c','d'])

In [68]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [69]:
states = ['Texas','Utha','California']

In [70]:
frame2.reindex(columns=states)

Texas  Utha  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [71]:
frame.reindex(columns=states)

Texas  Utha  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [72]:
frame.loc[['a','b','c','d'], states]

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

In [73]:
frame.loc?

In [74]:
obj = pd.Series(np.arange(5), index = ['a','b','c','d','e'])

In [75]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [76]:
new_obj = obj.drop('c')

In [77]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: int32

In [78]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=['Ohio','Colorado','Utah','New York'], columns=['one','two','three','four'])

In [79]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [80]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [81]:
ser = pd.Series(np.arange(3.))

In [82]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [83]:
ser[-1]

KeyError: -1

In [85]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])

In [86]:
ser2[-1]

2.0

In [87]:
ser[:1]

0    0.0
dtype: float64

In [88]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [89]:
ser.iloc[:1]

0    0.0
dtype: float64

In [90]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))

In [91]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [92]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

In [93]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [94]:
df2.loc[1,'b'] = np.nan

In [95]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [96]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [97]:
arr = np.arange(12.).reshape((3,4))

In [98]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [99]:
arr[0]

array([0., 1., 2., 3.])

In [100]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [101]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index = ['Utah','Ohio','Texas','Oregon'])

In [102]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [104]:
series = frame.iloc[0]

In [105]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [106]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [112]:
series2 = pd.Series(np.arange(3), index = ['b','e','f'])

In [113]:
series2

b    0
e    1
f    2
dtype: int32

In [114]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [115]:
series3 = frame['d']

In [118]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [121]:
frame = pd.DataFrame(np.random.randn(4,3), columns = list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [122]:
frame

b         d         e
Utah    0.077032  0.973763 -1.162077
Ohio    1.856707  0.049773  0.282244
Texas  -1.109842  0.799820 -0.254963
Oregon  0.031659  0.967276  0.465848

In [123]:
np.abs(frame)

b         d         e
Utah    0.077032  0.973763  1.162077
Ohio    1.856707  0.049773  0.282244
Texas   1.109842  0.799820  0.254963
Oregon  0.031659  0.967276  0.465848

In [124]:
f = lambda x : x.max() - x.min()

In [125]:
frame.apply(f)

b    2.966549
d    0.923990
e    1.627924
dtype: float64

In [126]:
frame.apply(f, axis='columns')

Utah      2.135840
Ohio      1.806935
Texas     1.909662
Oregon    0.935617
dtype: float64

In [127]:
def f(x) :
    return pd.Series([x.min(), x.max()], index=['min','max'])

In [128]:
frame.apply(f)

b         d         e
min -1.109842  0.049773 -1.162077
max  1.856707  0.973763  0.465848

In [129]:
format = lambda x : '%.2f' % x

In [130]:
frame.applymap(format)

b     d      e
Utah     0.08  0.97  -1.16
Ohio     1.86  0.05   0.28
Texas   -1.11  0.80  -0.25
Oregon   0.03  0.97   0.47

In [131]:
frame['e'].map(format)

Utah      -1.16
Ohio       0.28
Texas     -0.25
Oregon     0.47
Name: e, dtype: object

In [132]:
obj = pd.Series([4,np.nan, 7, np.nan, -3, 2])

In [133]:
obj.sort_values(ascending=False)

2    7.0
0    4.0
5    2.0
4   -3.0
1    NaN
3    NaN
dtype: float64

In [134]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [135]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [136]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [137]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [138]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])

In [139]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [140]:
obj.index.is_unique

False

In [141]:
obj['a']

a    0
a    1
dtype: int64

In [142]:
obj['c']

4

In [143]:
df = pd.DataFrame([[1.4, np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]], index = ['a','b','c','d'], columns = ['one','two'])

In [144]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [145]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [146]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [148]:
df.idxmax()

one    b
two    d
dtype: object

In [149]:
idxmax?

Object `idxmax` not found.


In [150]:
df.idxmax?

In [156]:
data = pd.DataFrame({'Qu1':[1,3,4,3,4], 'Qu2':[2,3,1,2,3],'Qu3':[1,5,2,4,4]})

In [157]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [158]:
result = data.apply(pd.value_counts).fillna(0)

In [159]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0